### ISSUE TITLE
No "character sheet" in compendium.

### ISSUE THREAD

**Issue by Lordofallic** [verrillion/DreadofNight#1]
Followed your 5 steps but can't complete step 5 because there is no compendium with "character sheet" only the Dread of Night adventure import which will not work and gets stuck at 8%.

**Comment by Vestium-R** [comment]
Hi @Lordofallic - I was able to reproduce your issue so thanks for the feedback! I've updated the module so please update it to find a new compendium with a getting started sheet and character sheet

This will resolve your import stopping at 8%
